# Generated by Django 2.2 on 2020-05-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200508_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
